steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Image
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-trace-demo:$SHORT_SHA', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Image
    args: ['push', 'gcr.io/$PROJECT_ID/fastapi-trace-demo:$SHORT_SHA']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy to Cloud Run
    args: [
      'run', 'deploy', 'fastapi-trace-demo',
      '--image', 'gcr.io/$PROJECT_ID/fastapi-trace-demo:$SHORT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/fastapi-trace-demo:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
